name: reactjs-vite Deployment # name of the workflo

on:
  push:
    branches:
      - main # branch name

jobs:
  deploy-react-to-ftp:
    runs-on: ubuntu-latest
    env:
      EXAMPLE: test # environment variable

    steps:
      # checkout the repository content to github runner
      - name: Checkout
        uses: actions/checkout@v2

      # setup nodejs environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "18.16.1"

      # cache the dependencies to speed up the build
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # install dependencies
      - name: Install dependencies
        run: npm i

      # build the react app
      - name: Build
        run: npm run build

      # deploy the react app to github pages
      - name: SFTP uploader                       # Upload to SFTP 
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrets.FTP_SERVER }}                  # Recommended to put the credentials in github secrets.
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          compress: false                            # Compression
          forceUpload: false                         # Optional, Force uploading all files, Default to false(upload only newer files).
          localDir: 'dist'                           # Required, Absolute or relative to cwd.
          remoteDir: '/home/www/test/'               # Required, Absolute path only. 
          exclude: 'node_modules/,.git*,.DS_Store'   # Optional. exclude patterns (glob) like .gitignore, use ',' to split, Default to ''.
